; Disassembly of "HMGB.gb"
; This file was created with:
; mgbdis v3.0 - Game Boy ROM disassembler by Matt Currie and contributors.
; https://github.com/mattcurrie/mgbdis

INCLUDE "hardware.inc"
INCLUDE "banks/bank_000.asm"
INCLUDE "banks/bank_001.asm"
INCLUDE "banks/bank_002.asm"
INCLUDE "banks/bank_003.asm"
INCLUDE "banks/bank_004.asm"
INCLUDE "banks/bank_005.asm"
INCLUDE "banks/bank_006.asm"
INCLUDE "banks/bank_007.asm"
INCLUDE "banks/bank_008.asm"
INCLUDE "banks/bank_009.asm"
INCLUDE "banks/bank_00a.asm"
INCLUDE "banks/bank_00b.asm"
INCLUDE "banks/bank_00c.asm"
INCLUDE "banks/bank_00d.asm"
INCLUDE "banks/bank_00e.asm"
INCLUDE "banks/bank_00f.asm"
INCLUDE "banks/bank_010.asm"
INCLUDE "banks/bank_011.asm"
INCLUDE "banks/bank_012.asm"
INCLUDE "banks/bank_013.asm"
INCLUDE "banks/bank_014.asm"
INCLUDE "banks/bank_015.asm"
INCLUDE "banks/bank_016.asm"
INCLUDE "banks/bank_017.asm"
INCLUDE "banks/bank_018.asm"
INCLUDE "banks/bank_019.asm"
INCLUDE "banks/bank_01a.asm"
INCLUDE "banks/bank_01b.asm"
INCLUDE "banks/bank_01c.asm"
INCLUDE "banks/bank_01d.asm"
INCLUDE "banks/bank_01e.asm"
INCLUDE "banks/bank_01f.asm"
INCLUDE "ram.asm"